export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
export const SET_MESSAGE = "SET_MESSAGE";

export const INCREASE = "SET_INCREASE";
export const DECREASE = "SET_DECRESE";

export const GET_ALL_SERVICE_TOPTEN = "GET_ALL_SERVICE_TOPTEN";
export const GET_ALL_SERVICE_COUNT = "GET_ALL_SERVICE_COUNT";
export const GET_ALL_SERVICE_COST = "GET_ALL_SERVICE_COST";
export const GET_ONE_FLEET = "GET_ONE_FLEET";
export const DELETE_ONE_FLEET = "DELETE_ONE_FLEET";
export const UPDATE_ONE_FLEET = "UPDATE_ONE_FLEET";
export const CREATE_ONE_FLEET = "CREATE_ONE_FLEET";
export const FLEET_LOADING = "FLEET_LOADING";
export const FLEET_LOADING_OFF = "FLEET_LOADING_OFF";
export const RESET_FLEET_DATA = "RESET_FLEET_DATA";
